### ISSUE TITLE
[to-do] 10.x monsters

### ISSUE THREAD

**Issue by OrtsImport** [orts/server#24]
<a href="https://github.com/EPuncker"><img src="https://avatars.githubusercontent.com/u/4684880?v=3" align="left" width="64" height="64" hspace="10"></img></a> **Issue by [EPuncker](https://github.com/EPuncker)**
_Wednesday Jul 09, 2014 at 02:21 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/895_

----

- [ ] Blood Beast
- [ ] Devourer
- [x] Execowtioner
- [ ] Glooth Anemone
- [ ] Glooth Blob
- [ ] Glooth Golem
- [ ] Greater Death Minion
- [ ] Lesser Death Minion
- [ ] Metal Gargoyle
- [x] Minotaur Amazon
- [x] Minotaur Hunter
- [x] Mooh'Tah Warrior
- [x] Moohtant
- [ ] Rot Elemental
- [ ] Rustheap Golem
- [ ] Superior Death Minion
- [ ] Walker
- [x] Worm Priestess
- [x] Bullwark
- [ ] Death Priest Shargon
- [ ] Glooth Fairy
- [ ] Lisa
- [ ] The Ravager
