### ISSUE TITLE
[to-do] Svargrond Arena

### ISSUE THREAD

**Issue by OrtsImport** [orts/server#26]
<a href="https://github.com/EPuncker"><img src="https://avatars.githubusercontent.com/u/4684880?v=3" align="left" width="64" height="64" hspace="10"></img></a> **Issue by [EPuncker](https://github.com/EPuncker)**
_Monday Jul 14, 2014 at 16:29 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/938_

----

- [ ] correct trophy message
- [ ] add so user can fight as many time as he want to
- [x] questlog?
- [ ] add last player name who did arena on statues
- [x] achievements

**Comment by HyphenMaster** [comment]
This issue was completely fixed?
