### ISSUE TITLE
[to-do] Unranked Killing in the Name of... tasks

### ISSUE THREAD

**Issue by OrtsImport** [orts/server#27]
<a href="https://github.com/EPuncker"><img src="https://avatars.githubusercontent.com/u/4684880?v=3" align="left" width="64" height="64" hspace="10"></img></a> **Issue by [EPuncker](https://github.com/EPuncker)**
_Tuesday Jul 15, 2014 at 21:29 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/952_

----

Info from: http://tibia.wikia.com/wiki/Killing_in_the_Name_of..._Quest/Spoiler

- Daniel Steelsoul tasks:
- [ ] 100 Trolls and Troll Champions
- [ ] 150 Goblins, Goblin Assassins, Goblin Scavengers
- [ ] 300 Rotworms and Carrion Worms
- [ ] 500 Cyclopes, Cyclops Drones, Cyclops Smiths

- Gabel
- [ ] 500 Green Djinn and Efreet

- Malor
- [ ] 500 Blue Djinn and Marid

- Raymond Striker
- [ ] 3,000 Pirate Marauders, Pirate Cutthroats, Pirate Buccaneers, Pirate Corsairs
- [ ] 3,000 Pirate Marauders, Pirate Cutthroats, Pirate Buccaneers, Pirate Corsairs

- Budrik
- [ ] 5,000 Minotaurs

- Lugri
- [ ] 4,000 Necromancers
- [ ] 1,000 Necromancers
