### ISSUE TITLE
[to-do] Telas

### ISSUE THREAD

**Issue by OrtsImport** [orts/server#28]
<a href="https://github.com/EPuncker"><img src="https://avatars.githubusercontent.com/u/4684880?v=3" align="left" width="64" height="64" hspace="10"></img></a> **Issue by [EPuncker](https://github.com/EPuncker)**
_Tuesday Jul 22, 2014 at 07:12 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/980_

----

http://tibia.wikia.com/wiki/Telas

- [ ] If you say "crystal pedestal" to him he will buy all pedestals in any colour state in your inventory.
- [ ] add transcripts
- [x] update item sale list
- [ ] make it only tradeable after completing Shadows of Yalahar Quest.
