### ISSUE TITLE
[to-do] Raids

### ISSUE THREAD

**Issue by OrtsImport** [orts/server#32]
<a href="https://github.com/EPuncker"><img src="https://avatars.githubusercontent.com/u/4684880?v=3" align="left" width="64" height="64" hspace="10"></img></a> **Issue by [EPuncker](https://github.com/EPuncker)**
_Wednesday Jul 30, 2014 at 05:56 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/1055_

----

Assigned to @EPuncker
I'll re-do/update most of them, just made this to keep track of the issue

http://tibia.wikia.com/wiki/Raids
Currently missing:

- [ ] The Evil Eye
- [ ] POI Bosses
- [ ] Djinn Raids near Ankrahmun
- [ ] Vampire Raid in Shadow Tomb
- [ ] Vampire Raid in Tarpit Tomb
- [ ] Troll Raid North-West of Carlin
- [ ] Wasp Raid North of Carlin
- [ ] Undead Raid on Ghostlands
- [ ] Orc Raid on Carlin (Gives amazon shield)
- [ ] Orc Raid on Femor Hills (Gives amazon armor and helmet)
- [ ] Hunter and Wild Warrior Raid on Femor Hills
- [ ] Amazon Raid North of Carlin
- [ ] Wasps in Darashia

more to come

**Comment by ninjalulz** [comment]
- [ ] [Serpent Spawn Raid](https://github.com/orts/server/issues/58)
- [ ] [Water Buffalo Raid](https://github.com/orts/server/issues/42)
