### ISSUE TITLE
Quests

### ISSUE THREAD

**Issue by OrtsImport** [orts/server#6]
<a href="https://github.com/Skillert"><img src="https://avatars.githubusercontent.com/u/7610136?v=3" align="left" width="64" height="64" hspace="10"></img></a> **Issue by [Skillert](https://github.com/Skillert)**
_Thursday Jun 12, 2014 at 12:14 GMT_
_Originally opened as https://github.com/PrinterLUA/FORGOTTENSERVER-ORTS/issues/685_

----

*Legends*:
- [ ] = means that the quest is not working as expected - waiting to get fixed(by anyone)
- [x] = means the quest is assumed to work as expected

~~strikethrough~~ = means the quest has been confirmed working as expected
IP = In progress

*Mainland Quests*:
- [x] [A Father's Burden](http://tibia.wikia.com/wiki/A_Father%27s_Burden_Quest) - 
- [ ] [A Piece of Cake](http://tibia.wikia.com/wiki/A_Piece_of_Cake) -
- [ ] [A Pirate's Death to Me](http://tibia.wikia.com/wiki/A_Pirate%27s_Death_to_Me) - 
- [x] [Adorned UH Rune](http://tibia.wikia.com/wiki/Adorned_UH_Rune_Quest) -
- [ ] [Adventurers Guild](http://tibia.wikia.com/wiki/Adventurers_Guild_Quest) - 
- [x] [Against the Spider Cult](http://tibia.wikia.com/wiki/Against_the_Spider_Cult_Quest) - 
- [ ] [Alawar's Vault Quest](http://tibia.wikia.com/wiki/Alawar%27s_Vault_Quest) - 
- [x] [An Interest In Botany](http://tibia.wikia.com/wiki/An_Interest_In_Botany_Quest) - 
- [ ] [An Uneasy Alliance](http://tibia.wikia.com/wiki/An_Uneasy_Alliance_Quest) - 
- [ ] [Annual Autumn Vintage](http://tibia.wikia.com/wiki/Annual_Autumn_Vintage) - 
- [ ] [Arito's Task](http://tibia.wikia.com/wiki/Arito%27s_Task_Quest) - 
- [ ] [Awash World Change](http://tibia.wikia.com/wiki/Awash_World_Change) - 
- [x] [Barbarian Arena](http://tibia.wikia.com/wiki/Barbarian_Arena_Quest) - #739 
- [x] [Barbarian Axe](http://tibia.wikia.com/wiki/Barbarian_Axe_Quest) - 
- [x] [Barbarian Test](http://tibia.wikia.com/wiki/Barbarian_Test_Quest) - 
- [x] [Battle Axe](http://tibia.wikia.com/wiki/Battle_Axe_Quest) - 
- [x] [Behemoth](http://tibia.wikia.com/wiki/Behemoth_Quest) - 
- [x] [Berserk Potion](http://tibia.wikia.com/wiki/Berserk_Potion_Quest) - 
- [x] [Berserker Treasure](http://tibia.wikia.com/wiki/Berserker_Treasure_Quest) - 
- [ ] [Bewitched](http://tibia.wikia.com/wiki/Bewitched) - 
- [ ] [Bigfoot's Burden](http://tibia.wikia.com/wiki/Bigfoot%27s_Burden_Quest/Spoiler) - #484 
- [x] [Black Knight](http://tibia.wikia.com/wiki/Black_Knight_Quest) - 
- [ ] [Blood Brothers](http://tibia.wikia.com/wiki/Blood_Brothers_Quest) - 
- [x] [Blood Herb](http://tibia.wikia.com/wiki/Blood_Herb_Quest) - 
- [x] [Braindeath](http://tibia.wikia.com/wiki/Braindeath_Quest) - 
- [x] [Children of the Revolution](http://tibia.wikia.com/wiki/Children_of_the_Revolution_Quest) - #687 
- [x] [Circle Room](http://tibia.wikia.com/wiki/Circle_Room_Quest) - 
- [x] [Crusader Helmet](http://tibia.wikia.com/wiki/Crusader_Helmet_Quest) - 
- [x] [Crystal Wand](http://tibia.wikia.com/wiki/Crystal_Wand_Quest) - 
- [x] [Darashia Dragon](http://tibia.wikia.com/wiki/Darashia_Dragon_Quest) - 
- [x] [Dark Armor](http://tibia.wikia.com/wiki/Dark_Armor_Quest) - 
- [ ] [Dark Trails](http://tibia.wikia.com/wiki/Dark_Trails_Quest) - 
- [x] [Dead Archer](http://tibia.wikia.com/wiki/Dead_Archer_Quest) - 
- [x] [Deeper Fibula](http://tibia.wikia.com/wiki/Deeper_Fibula_Quest) - 
- [ ] [Deeplings World Change](http://tibia.wikia.com/wiki/Deeplings_World_Change) - 
- [ ] [Demon's Lullaby](http://tibia.wikia.com/wiki/Demon%27s_Lullaby) - 
- [x] [Demon Helmet](http://tibia.wikia.com/wiki/Demon_Helmet_Quest/Spoiler) - #536 
- [ ] [Demon Wars World Change](http://tibia.wikia.com/wiki/Demon_Wars_World_Change) - #1270
- [ ] [Devil Helmet](http://tibia.wikia.com/wiki/Devil_Helmet_Quest) - 
- [x] [Double Hero](http://tibia.wikia.com/wiki/Double_Hero_Quest) - 
- [ ] [Draconia](http://tibia.wikia.com/wiki/Draconia_Quest) - 
- [x] [Dragon Tower](http://tibia.wikia.com/wiki/Dragon_Tower_Quest) - 
- [x] [Dreamer's Challenge](http://tibia.wikia.com/wiki/Dreamer%27s_Challenge_Quest/Spoiler) - #494 #509 #538 
- [x] [Edron Goblin](http://tibia.wikia.com/wiki/Edron_Goblin_Quest) - 
- [x] [Elemental Sphere](http://tibia.wikia.com/wiki/Elemental_Spheres_Quest/Spoiler) - #494 #538 #601
- [x] [Elephant Tusk](http://tibia.wikia.com/wiki/Elephant_Tusk_Quest) - 
- [x] [Elvenbane](http://tibia.wikia.com/wiki/Elvenbane_Quest) - 
- [x] [Emperor's Cookies](http://tibia.wikia.com/wiki/Emperor%27s_Cookies_Quest) - #1287
- [x] [Explorer Brooch](http://tibia.wikia.com/wiki/Explorer_Brooch_Quest) - 
- [x] [Fanfare](http://tibia.wikia.com/wiki/Fanfare_Quest) - 
- [x] [Fire Axe](http://tibia.wikia.com/wiki/Fire_Axe_Quest) - 
- [x] [Fishing Box](http://tibia.wikia.com/wiki/Fishing_Box_Quest) - 
- [x] [Formorgar Mine](http://tibia.wikia.com/wiki/Formorgar_Mine_Quest) - 
- [x] [Formorgar Mines Hoist](http://tibia.wikia.com/wiki/Formorgar_Mines_Hoist_Quest) - 
- [x] [Frost Dragon](http://tibia.wikia.com/wiki/Frost_Dragon_Quest) - 
- [x] [Geomancer](http://tibia.wikia.com/wiki/Geomancer_Quest) - #783 
- [x] [Ghoul Room](http://tibia.wikia.com/wiki/Ghoul_Room_Quest) - 
- [x] [Giant Smithhammer](http://tibia.wikia.com/wiki/Giant_Smithhammer_Quest) - 
- [ ] [Glooth Engineer Outfits](http://tibia.wikia.com/wiki/Glooth_Engineer_Outfits_Quest) - 
- [ ] [Goblin Merchant](http://tibia.wikia.com/wiki/Goblin_Merchant_Quest) - 
- [x] [Griffin Shield](http://tibia.wikia.com/wiki/Griffin_Shield_Quest) - 
- [x] [Heaven Blossom](http://tibia.wikia.com/wiki/Heaven_Blossom_Quest) - #784 
- [ ] [Hive Born World Change](http://tibia.wikia.com/wiki/Hive_Born_World_Change) - 
- [ ] [Hoggle's Garden](http://tibia.wikia.com/wiki/Hoggle%27s_Garden_Quest) - 
- [ ] [Horse Station World Change](http://tibia.wikia.com/wiki/Horse_Station_World_Change) - 
- [x] [Hot Cuisine](http://tibia.wikia.com/wiki/Hot_Cuisine_Quest) - 
- [x] [Hydra Egg](http://tibia.wikia.com/wiki/Hydra_Egg_Quest) - 
- [ ] [Insectoid Invasion World Change](http://tibia.wikia.com/wiki/Insectoid_Invasion_World_Change) - 
- [ ] [Insectoid Outfits](http://tibia.wikia.com/wiki/Insectoid_Outfits_Quest) - 
- [x] [Into the Bone Pit](http://tibia.wikia.com/wiki/Into_The_Bone_Pit_Quest) - 
- [x] [Inukaya](http://tibia.wikia.com/wiki/Inukaya_Quest) - 
- [x] [Iron Hammer](http://tibia.wikia.com/wiki/Iron_Hammer_Quest) - #788 
- [x] [Iron Helmet](http://tibia.wikia.com/wiki/Iron_Helmet_Quest) - 
- [x] [Iron Ore](http://tibia.wikia.com/wiki/Iron_Ore_Quest) - #789 
- [x] [Isle of the Mists](http://tibia.wikia.com/wiki/Isle_of_the_Mists_Quest) - 
- [ ] [Jack to the Future](http://tibia.wikia.com/wiki/Jack_to_the_Future_Quest) - 
- [x] [Killing in the name of... tasks](http://tibia.wikia.com/wiki/Killing_in_the_Name_of..._Quest/Spoiler) - Does not give boss points / Not possible to kill bosses after a task has been completed(?)
- [ ] [Kingdom of Kormarak](http://tibia.wikia.com/wiki/Kingdom_of_Kormarak_Quest) - 
- [ ] [Kissing a Pig](http://tibia.wikia.com/wiki/Kissing_a_Pig_Quest) - 
- [x] [Koshei the Deathless](http://tibia.wikia.com/wiki/Koshei_The_Deathless_Quest) - 
- [ ] [Last Creep Standing](http://tibia.wikia.com/wiki/Last_Creep_Standing) - 
- [x] [Life Ring](http://tibia.wikia.com/wiki/Life_Ring_Quest) - 
- [x] [Lion Trophy](http://tibia.wikia.com/wiki/Lion_Trophy_Quest) - 
- [x] [Lone Medusa](http://tibia.wikia.com/wiki/Lone_Medusa_Quest) - 
- [x] [Longsword](http://tibia.wikia.com/wiki/Longsword_Quest) - 
- [ ] [Loose Ends](http://tibia.wikia.com/wiki/Loose_Ends_Quest) - 
- [ ] [Machinery of War](http://tibia.wikia.com/wiki/Machinery_of_War_Quest) - 
- [x] [Mad Mage Room](http://tibia.wikia.com/wiki/Mad_Mage_Room_Quest) - #852 
- [x] [Mastermind Potion](http://tibia.wikia.com/wiki/Mastermind_Potion_Quest) - 
- [x] [Medusa Shield](http://tibia.wikia.com/wiki/Medusa_Shield_Quest) - 
- [ ] [Meriana](http://tibia.wikia.com/wiki/Meriana_Quest) - 
- [ ] [Minotaur Leather](http://tibia.wikia.com/wiki/Minotaur_Leather_Quest) - 
- [ ] [Mintwallin Cyclops](http://tibia.wikia.com/wiki/Mintwallin_Cyclops_Quest) - 
- [x] [Naginata](http://tibia.wikia.com/wiki/Naginata_Quest) - #782 
- [x] [Noble Armor](http://tibia.wikia.com/wiki/Noble_Armor_Quest) - 
- [ ] [Nomads Land](http://tibia.wikia.com/wiki/Nomads_Land_Quest) - 
- [ ] [Opticording Sphere](http://tibia.wikia.com/wiki/Opticording_Sphere_Quest) - 
- [ ] [Oramond](http://tibia.wikia.com/wiki/Oramond_Quest) - 
- [x] [Orc Fortress](http://tibia.wikia.com/wiki/Orc_Fortress_Quest) - 
- [x] [Orc Shaman](http://tibia.wikia.com/wiki/Orc_Shaman_Quest) - 
- [x] [Ornamented Shield](http://tibia.wikia.com/wiki/Ornamented_Shield_Quest) - 
- [ ] [Overhunting World Change](http://tibia.wikia.com/wiki/Overhunting_World_Change) - 
- [ ] [Panpipe](http://tibia.wikia.com/wiki/Panpipe_Quest) - 
- [x] [Parchment Room](http://tibia.wikia.com/wiki/Parchment_Room_Quest/Spoiler) - #536 
- [ ] [Pilgrimage of Ashes](http://tibia.wikia.com/wiki/Pilgrimage_of_Ashes_Quest) - 
- [x] [Plate Armor](http://tibia.wikia.com/wiki/Plate_Armor_Quest) - 
- [x] [Poison Daggers](http://tibia.wikia.com/wiki/Poison_Daggers_Quest) - 
- [x] [Power Bolts](http://tibia.wikia.com/wiki/Power_Bolts_Quest) - 
- [x] [Power Ring](http://tibia.wikia.com/wiki/Power_Ring_Quest) - 
- [x] [Purple Tome](http://tibia.wikia.com/wiki/Purple_Tome_Quest) - 
- [ ] [Rathleton](http://tibia.wikia.com/wiki/Rathleton_Quest) - 
- [ ] [Realm of Dreams](http://tibia.wikia.com/wiki/Realm_of_Dreams_Quest/Spoiler) - #682 
- [ ] [Research and Development](http://tibia.wikia.com/wiki/Research_and_Development_Quest) - 
- [x] [Rest in Hallowed Ground](http://tibia.wikia.com/wiki/Rest_in_Hallowed_Ground_Quest) - 
- [x] [Ring](http://tibia.wikia.com/wiki/Ring_Quest) - 
- [ ] [Rise of Devovorga](http://tibia.wikia.com/wiki/Rise_of_Devovorga) - 
- [ ] [Roshamuul](http://tibia.wikia.com/wiki/Roshamuul_Quest) - #451 
- [ ] [Rottin Wood and the Married Men](http://tibia.wikia.com/wiki/Rottin_Wood_and_the_Married_Men_Quest) - 
- [x] [Sam's Old Backpack](http://tibia.wikia.com/wiki/Sam%27s_Old_Backpack_Quest) - 
- [x] [Scale Armor](http://tibia.wikia.com/wiki/Scale_Armor_Quest) - #791 
- [ ] [Sea of Light](http://tibia.wikia.com/wiki/Sea_of_Light_Quest) - 
- [x] [Secret Service](http://tibia.wikia.com/wiki/Secret_Service_Quest/Spoiler) - #494 
- [ ] [Serpentine Tower](http://tibia.wikia.com/wiki/Serpentine_Tower_Quest) - 
- [ ] [Shadows of Yalahar](http://tibia.wikia.com/wiki/Shadows_of_Yalahar_Quest) - 
- [x] [Shaman Treasure](http://tibia.wikia.com/wiki/Shaman_Treasure_Quest) - 
- [ ] [Silver Amulet](http://tibia.wikia.com/wiki/Silver_Amulet_Quest) - 
- [x] [Silver Brooch](http://tibia.wikia.com/wiki/Silver_Brooch_Quest) - 
- [ ] [Sinatuki](http://tibia.wikia.com/wiki/Sinatuki_Quest) - 
- [x] [Six Rubies](http://tibia.wikia.com/wiki/Six_Rubies_Quest) - #787 
- [x] [Skeleton Decoration](http://tibia.wikia.com/wiki/Skeleton_Decoration_Quest) - 
- [x] [Skull of Ratha](http://tibia.wikia.com/wiki/Skull_of_Ratha_Quest) - 
- [x] [Small Ruby](http://tibia.wikia.com/wiki/Small_Ruby_Quest) - #786 
- [x] [Spike Sword](http://tibia.wikia.com/wiki/Spike_Sword_Quest) - 
- [ ] [Spike Tasks](http://tibia.wikia.com/wiki/Spike_Tasks_Quest) - 
- [ ] [Spirithunters](http://tibia.wikia.com/wiki/Spirithunters_Quest) - 
- [ ] [Spring Into Life](http://tibia.wikia.com/wiki/Spring_into_Life) - 
- [ ] [Steal From Thieves](http://tibia.wikia.com/wiki/Steal_From_Thieves_Quest) - 
- [x] [Stealth Ring](http://tibia.wikia.com/wiki/Stealth_Ring_Quest) - 
- [ ] [Steamship World Change](http://tibia.wikia.com/wiki/Steamship_World_Change) - 
- [x] [Steel Helmet](http://tibia.wikia.com/wiki/Steel_Helmet_Quest) - #785 
- [x] [Strong Potions](http://tibia.wikia.com/wiki/Strong_Potions_Quest) - 
- [ ] [Swamp Fever World Change](http://tibia.wikia.com/wiki/Swamp_Fever_World_Change) - 
- [x] [Thais Lighthouse](http://tibia.wikia.com/wiki/Thais_Lighthouse_Quest) - 
- [x] [The Ancient Tombs](http://tibia.wikia.com/wiki/The_Ancient_Tombs_Quest) - 
- [x] [The Annihilator](http://tibia.wikia.com/wiki/The_Annihilator_Quest) - 
- [x] [The Ape City](http://tibia.wikia.com/wiki/The_Ape_City_Quest) - 
- [x] [The Blessed Stake](http://tibia.wikia.com/wiki/The_Blessed_Stake_Quest) - 
- [ ] [The Colours of Magic](http://tibia.wikia.com/wiki/The_Colours_of_Magic) - 
- [ ] [The Demon Oak](http://tibia.wikia.com/wiki/The_Demon_Oak_Quest) - #575 
- [x] [The Desert Dungeon](http://tibia.wikia.com/wiki/The_Desert_Dungeon_Quest) - 
- [x] [The Djinn War - Efreet Faction](http://tibia.wikia.com/wiki/The_Djinn_War_-_Efreet_Faction) - #647 
- [x] [The Djinn War - Marid Faction](http://tibia.wikia.com/wiki/The_Djinn_War_-_Marid_Faction) - 
- [x] [The Explorer Society](http://tibia.wikia.com/wiki/The_Explorer_Society_Quest) - #773 
- [x] [The Exterminator](http://tibia.wikia.com/wiki/The_Exterminator_Quest) - 
- [x] [The Gravedigger of Drefia](http://tibia.wikia.com/wiki/The_Gravedigger_of_Drefia_Quest/Spoiler) - #659 #763 
- [x] [The Hidden City of Beregar](http://tibia.wikia.com/wiki/The_Hidden_City_of_Beregar_Quest/Spoiler) - #652 #662 #797 
- [x] [The Hunt for the Sea Serpent](http://tibia.wikia.com/wiki/The_Hunt_for_the_Sea_Serpent_Quest) - 
- [x] [The Ice Islands](http://tibia.wikia.com/wiki/The_Ice_Islands_Quest) - 
- [ ] [The Isle of Evil](http://tibia.wikia.com/wiki/The_Isle_of_Evil_Quest) - 
- [ ] [The Lightbearer](http://tibia.wikia.com/wiki/The_Lightbearer) - 
- [ ] [The Mage's Tower World Change](http://tibia.wikia.com/wiki/The_Mage%27s_Tower_World_Change) - 
- [ ] [The Mummy's Curse World Change](http://tibia.wikia.com/wiki/The_Mummy%27s_Curse_World_Change) - 
- [x] [The New Frontier](http://tibia.wikia.com/wiki/The_New_Frontier_Quest) - 
- [x] [The Outlaw Camp](http://tibia.wikia.com/wiki/The_Outlaw_Camp_Quest/Spoiler) - #405 
- [ ] [The Paradox Tower](http://tibia.wikia.com/wiki/The_Paradox_Tower_Quest) - #852 
- [x] [Pits of Inferno](http://tibia.wikia.com/wiki/Pits_Of_Inferno_Quest/Spoiler) - #655 
- [x] [The Postman Missions](http://tibia.wikia.com/wiki/The_Postman_Missions_Quest) - 
- [x] [The Queen of the Banshees](http://tibia.wikia.com/wiki/The_Queen_of_the_Banshees_Quest) - 
- [ ] [The Repenters](http://tibia.wikia.com/wiki/The_Repenters_Quest) - 
- [ ] [The Scatterbrained Sorcerer](http://tibia.wikia.com/wiki/The_Scatterbrained_Sorcerer_Quest) - 
- [ ] [The Shattered Isles](http://tibia.wikia.com/wiki/The_Shattered_Isles_Quest) - 
- [ ] [The Spirit Will Get You](http://tibia.wikia.com/wiki/The_Spirit_Will_Get_You_Quest) - 
- [x] [The Thieves Guild](http://tibia.wikia.com/wiki/The_Thieves_Guild_Quest/Spoiler) - 
- [x] [The Travelling Trader](http://tibia.wikia.com/wiki/The_Travelling_Trader_Quest) - 
- [x] [The Ultimate Booze](http://tibia.wikia.com/wiki/The_Ultimate_Booze_Quest) - 
- [x] [The White Raven Monastery](http://tibia.wikia.com/wiki/The_White_Raven_Monastery_Quest) - 
- [ ] [Their Master's Voice World Change](http://tibia.wikia.com/wiki/Their_Master%27s_Voice_World_Change) - 
- [ ] [Thornfire World Change](http://tibia.wikia.com/wiki/Thornfire_World_Change) - 
- [x] [Throwing Star](http://tibia.wikia.com/wiki/Throwing_Star_Quest) - 
- [x] [Time Ring](http://tibia.wikia.com/wiki/Time_Ring_Quest) - 
- [ ] [To Appease the Mighty](http://tibia.wikia.com/wiki/To_Appease_the_Mighty_Quest) - 
- [ ] [To Blind the Enemy](http://tibia.wikia.com/wiki/To_Blind_the_Enemy_Quest) - 
- [x] [To Outfox a Fox](http://tibia.wikia.com/wiki/To_Outfox_a_Fox_Quest) - 
- [x] [Tomes of Knowledge](http://tibia.wikia.com/wiki/Tomes_of_Knowledge_Quest) - 
- [ ] [Top of the City](http://tibia.wikia.com/wiki/Top_of_the_City_Quest) - 
- [ ] [Tower Defence](http://tibia.wikia.com/wiki/Tower_Defence_Quest) - 
- [ ] [Treasure Hunt](http://tibia.wikia.com/wiki/Treasure_Hunt_Quest) - 
- [ ] [Treasure Island](http://tibia.wikia.com/wiki/Treasure_Island_Quest) - 
- [ ] [Triangle Tower](http://tibia.wikia.com/wiki/Triangle_Tower_Quest) - 
- [x] [Troll Cave](http://tibia.wikia.com/wiki/Troll_Cave_Quest) - 
- [ ] [Troll Sabotage](http://tibia.wikia.com/wiki/Troll_Sabotage_Quest) - 
- [ ] [Twisted Waters World Change](http://tibia.wikia.com/wiki/Twisted_Waters_World_Change) - 
- [x] [Unnatural Selection](http://tibia.wikia.com/wiki/Unnatural_Selection_Quest) - 
- [ ] [Vampire Hunter](http://tibia.wikia.com/wiki/Vampire_Hunter_Quest) - 
- [x] [Vampire Shield](http://tibia.wikia.com/wiki/Vampire_Shield_Quest) - 
- [ ] [Venore Daily Tasks](http://tibia.wikia.com/wiki/Venore_Daily_Tasks_Quest) - 
- [x] [Voodoo Doll](http://tibia.wikia.com/wiki/Voodoo_Doll_Quest) - 
- [ ] [War Against the Hive](http://tibia.wikia.com/wiki/War_Against_the_Hive_Quest) - #1256
- [x] [Waterfall](http://tibia.wikia.com/wiki/Waterfall_Quest) - 
- [x] [Waterskin of Mead](http://tibia.wikia.com/wiki/Waterskin_of_Mead_Quest) - 
- [x] [Wedding Ring](http://tibia.wikia.com/wiki/Wedding_Ring_Quest) - 
- [x] [White Pearl](http://tibia.wikia.com/wiki/White_Pearl_Quest) - 
- [x] [Wrath of The Emperor](http://tibia.wikia.com/wiki/Wrath_of_the_Emperor_Quest/Spoiler) - #151 

*Mainland Exchange Quests*:
- [ ] [Exchange](http://tibia.wikia.com/wiki/Exchange_Quests) - 
- [x] [Marlin Trophy](http://tibia.wikia.com/wiki/Marlin_Trophy_Quest) - 
- [x] [Obsidian Knife](http://tibia.wikia.com/wiki/Obsidian_Knife_Quest) - 
- [x] [The Mermaid Marina](http://tibia.wikia.com/wiki/The_Mermaid_Marina_Quest) - 
- [x] [The Sweaty Cyclops](http://tibia.wikia.com/wiki/The_Sweaty_Cyclops_Quest) - 

*Mainland Addon Quests*:
- [x] [Barbarian Outfits](http://tibia.wikia.com/wiki/Barbarian_Outfits_Quest) - #743 
- [x] [Citizen Outfits](http://tibia.wikia.com/wiki/Citizen_Outfits_Quest) - #743 
- [x] [Druid Outfits](http://tibia.wikia.com/wiki/Druid_Outfits_Quest) - #743 
- [x] [Hunter Outfits](http://tibia.wikia.com/wiki/Hunter_Outfits_Quest) - #743 
- [x] [Knight Outfits](http://tibia.wikia.com/wiki/Knight_Outfits_Quest) - #743 
- [x] [Mage Outfits](http://tibia.wikia.com/wiki/Mage_Outfits_Quest) - #743 
- [x] [Nobleman Outfits](http://tibia.wikia.com/wiki/Nobleman_Outfits_Quest) - #743 
- [x] [Oriental Outfits](http://tibia.wikia.com/wiki/Oriental_Outfits_Quest) - #743 
- [x] [Summoner Outfits](http://tibia.wikia.com/wiki/Summoner_Outfits_Quest) - #743 
- [x] [Warrior Outfits](http://tibia.wikia.com/wiki/Warrior_Outfits_Quest) - #743 
- [x] [Wizard Outfits](http://tibia.wikia.com/wiki/Wizard_Outfits_Quest) - #743 

*Mainland Outfit Quests*:
- [x] [Afflicted Outfits](http://tibia.wikia.com/wiki/Afflicted_Outfits_Quest) - #743 
- [x] [Assassin Outfits](http://tibia.wikia.com/wiki/Assassin_Outfits_Quest) - #743 
- [x] [Beggar Outfits](http://tibia.wikia.com/wiki/Beggar_Outfits_Quest) - #743 
- [x] [Brotherhood Outfits](http://tibia.wikia.com/wiki/Brotherhood_Outfits_Quest) - #743 
- [x] [Crystal Warlord Outfits](http://tibia.wikia.com/wiki/Crystal_Warlord_Outfits_Quest) - #743 
- [x] [Demon Outfits](http://tibia.wikia.com/wiki/Demon_Outfits_Quest) - #743 
- [ ] [Dream Warden Outfits](http://tibia.wikia.com/wiki/Dream_Warden_Outfits_Quest) - #743 
- [ ] [Elementalist Outfits](http://tibia.wikia.com/wiki/Elementalist_Outfits_Quest) - #743 
- [x] [Yalaharian Outfits](http://tibia.wikia.com/wiki/In_Service_of_Yalahar_Quest) - #743 
- [ ] [Deepling Outfits](http://tibia.wikia.com/wiki/Liquid_Black_Quest) - #743 
- [x] [Nightmare Outfits](http://tibia.wikia.com/wiki/Nightmare_Outfits_Quest) - #743 
- [x] [Norseman Outfits](http://tibia.wikia.com/wiki/Norseman_Outfits_Quest) - #743 
- [x] [Pirate Outfits](http://tibia.wikia.com/wiki/Pirate_Outfits_Quest) - #743 
- [x] [Shaman Outfits](http://tibia.wikia.com/wiki/Shaman_Outfits_Quest) - #743 
- [x] [Soil Guardian Outfits](http://tibia.wikia.com/wiki/Soil_Guardian_Outfits_Quest) - #743 
- [x] [Demon Hunter Outfits](http://tibia.wikia.com/wiki/The_Inquisition_Quest) - #743 
- [x] [Warmaster Outfits](http://tibia.wikia.com/wiki/Warmaster_Outfits_Quest) - #743 
- [x] [Wayfarer Outfits](http://tibia.wikia.com/wiki/Wayfarer_Outfits_Quest) - #743 
- [x] [Jester Outfits](http://tibia.wikia.com/wiki/What_a_Foolish_Quest) - #743
