### ISSUE TITLE
Quest bugs

### ISSUE THREAD

**Issue by ninjalulz** [orts/server#76]
- [ ] [Postman Mission 7(+)?](https://github.com/orts/server/issues/72)
- [ ] [Banshee Quest 3rd seal](https://github.com/orts/server/issues/59)
- [ ] [Yalahar 2nd mission](https://github.com/orts/server/issues/50)
- [ ] [Rework Bigfoot Burden's Quest](https://github.com/orts/server/issues/47)
- [ ] [Gravedigger Vol.3, Ch:4 (might as well rewrite most missions)](https://github.com/orts/server/issues/39)
- [ ] [Liquid Black Quest](https://github.com/orts/server/issues/22)

**Comment by EPuncker** [comment]
liquid black is a pain in the a*s since it requires tracking of several states of deepeling maps :( good luck tho to anyone willing to do that xD

**Comment by Schiffers** [comment]
put in your list:
Shadows of Yalahar Quest

**Comment by WibbenZ** [comment]
You can check off Banshee quest, just checked it and it works for me "17:41 Your questlog has been updated.".

**Comment by WibbenZ** [comment]
@ninjalulz do you know what the problem is with the postman mission?

**Comment by rikitrini** [comment]
@ninjalulz bigfoot burden questlog not working, gnomewart dont talk but work , and gnomelvis not working and teleport above gnomelvis not working >.<

**Comment by rikitrini** [comment]
@ninjalulz  in service of yalahar quest mission 3 can't take the palimuth note because can't open the door and i removed door and chest its empty

**Comment by rikitrini** [comment]
@ninjalulz children of the revolution mission 4 after use the greasse oil the levers still dont moving

**Comment by rikitrini** [comment]
@ninjalulz fixed children of revolution was a bug on line 25 targetitemid  ~=  change it for double == and works fine^^ if you can would be nice if you can add bigfoots burden questlog

**Comment by EPuncker** [comment]
add to list, add the "mushroom beer" to bigfoot quest

**Comment by rikitrini** [comment]
i maked right now all tasks and they are working all perfect the only problem its on gnomission they say fine, i grant yout o acces to warzones but when i try to enter i can't
